language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t runzeliu29/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run runzeliu29/react-test npn test -- --coverage

  after_success:
    - docker build -t runzeliu29/multi-client ./client
    - docker build -t runzeliu29/multi-nginx ./nginx
    - docker build -t runzeliu29/multi-server ./server
    - docker build -t runzeliu29/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push runzeliu29/multi-client
    - docker push runzeliu29/multi-nginx
    - docker push runzeliu29/multi-server
    - docker push runzeliu29/multi-worker
